import path from "node:path";
import { fileURLToPath } from "node:url";

export const uploadRoot = fileURLToPath(new URL("../../uploads/", import.meta.url));

// Resolve only files generated by this API, in the authenticated owner's folder.
// Never fetch an arbitrary URL supplied through profile or company settings.
export function ownedImagePath(url, { agencyId, purpose = "logo", userId } = {}) {
  if (!url || !Number.isInteger(agencyId) || agencyId < 1) return null;
  try {
    const parsed = new URL(url);
    const api = new URL(process.env.API_URL || "http://localhost:4000");
    if (parsed.origin !== api.origin || parsed.search || parsed.hash) return null;
    const prefix = `/uploads/${agencyId}/${purpose}/${purpose === "avatar" ? `${userId}/` : ""}`;
    if (!parsed.pathname.startsWith(prefix)) return null;
    const name = parsed.pathname.slice(prefix.length);
    if (!/^\d+-[a-f0-9]{16}\.(png|jpg|webp)$/.test(name)) return null;
    return path.join(uploadRoot, String(agencyId), purpose, ...(purpose === "avatar" ? [String(userId)] : []), name);
  } catch {
    return null;
  }
}
