import { useEffect,useState } from "react";
import api from "../lib/api.js";
export default function AdminAudit(){
  const [page,setPage]=useState(1),[data,setData]=useState({items:[],hasMore:false}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);setError("");api.get("/platform/actions",{params:{page}}).then(({data})=>{if(active)setData(data);}).catch(()=>{if(active)setError("Journal inaccessible. Réessayez.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[page,refresh]);
  return <section className="card space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-heading text-lg font-semibold">Interventions administrateur</h3><p className="text-sm text-slate-500">Consultations des données, changements d’accès et configuration GA4.</p></div><button className="btn-secondary" disabled={loading} onClick={()=>setRefresh(n=>n+1)}>Actualiser</button></div>
    {loading?<p role="status">Chargement…</p>:error?<p role="alert" className="text-sm text-red-600">{error}</p>:!data.items.length?<p className="text-sm text-slate-500">Aucune intervention enregistrée.</p>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase text-slate-500">{["Date","Administrateur","Entreprise","Action","Motif / détail"].map(label=><th key={label} className="pb-3 pr-4">{label}</th>)}</tr></thead><tbody>{data.items.map(row=><tr key={row.id} className="border-b border-slate-100"><td className="py-3 pr-4 whitespace-nowrap">{new Date(row.created_at).toLocaleString("fr-CA")}</td><td className="py-3 pr-4">{row.actor}</td><td className="py-3 pr-4">{row.agency}</td><td className="py-3 pr-4">{row.action==="ADMIN_VIEW"?"Consultation":row.action==="GA4_CONFIG"?"Configuration GA4":"Modification"} · {row.entity_type} #{row.entity_id}</td><td className="py-3 pr-4"><p>{row.metadata?.reason||"Consultation des données"}</p>{row.action!=="ADMIN_VIEW"&&<details className="mt-1 text-xs text-slate-500"><summary className="cursor-pointer">Voir les changements</summary><pre className="mt-2 whitespace-pre-wrap break-all">{JSON.stringify({avant:row.metadata?.before,après:row.metadata?.after},null,2)}</pre></details>}</td></tr>)}</tbody></table></div>}
    <div className="flex justify-between items-center"><button className="btn-secondary" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Précédent</button><span className="text-sm text-slate-500">Page {page}</span><button className="btn-secondary" disabled={loading||!!error||!data.hasMore} onClick={()=>setPage(p=>p+1)}>Suivant</button></div>
  </section>;
}
