import { useEffect,useState } from "react";
import { Line } from "react-chartjs-2";
import api from "../lib/api.js";
export default function GoogleAnalyticsPanel(){
  const [config,setConfig]=useState(null),[report,setReport]=useState(null),[days,setDays]=useState(30),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);
  const [busy,setBusy]=useState(false),[saveError,setSaveError]=useState(""),[saved,setSaved]=useState(""),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);
  useEffect(()=>{let active=true;api.get("/platform/analytics/config").then(({data})=>{if(active)setConfig(data);}).catch(()=>{if(active)setSaveError("Configuration inaccessible. Actualisez la page.");});return()=>{active=false;};},[]);
  useEffect(()=>{let active=true;setLoading(true);setError("");api.get("/platform/analytics/report",{params:{days}}).then(({data})=>{if(active)setReport(data);}).catch(e=>{if(active)setError(e.response?.data?.message||"Rapport inaccessible.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[days,refresh]);
  async function save(event){event.preventDefault();if(busy)return;setBusy(true);setSaveError("");setSaved("");try{const {data}=await api.put("/platform/analytics/config",{enabled:config.enabled,measurementId:config.measurementId.trim().toUpperCase(),propertyId:config.propertyId.trim(),reason,manualMeasurementConfirmed:confirmed});setConfig(data);setSaved("Configuration GA4 enregistrée.");setReason("");setRefresh(n=>n+1);}catch(e){setSaveError(e.response?.data?.message||"Enregistrement impossible.");}finally{setBusy(false);}}
  const options={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true},x:{grid:{display:false}}}};
  return <div className="space-y-4">
    <section className="card"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-heading text-xl font-semibold">Google Analytics 4</h3><p className="mt-1 text-sm text-slate-500">Fréquentation du site, acquisition et pages consultées. Ces données proviennent de Google, séparément du trafic API du CRM.</p></div><div className="flex gap-2"><select aria-label="Période GA4" className="field-input w-auto" value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>{n} jours</option>)}</select><button className="btn-secondary" disabled={loading} onClick={()=>setRefresh(n=>n+1)}>Actualiser</button></div></div></section>
    {loading?<section className="card"><p role="status">Chargement des statistiques GA4…</p></section>:error?<section className="card"><p role="alert" className="text-sm text-red-600">{error}</p></section>:!report?.configured?<section className="card"><h4 className="font-semibold">Connexion Google à compléter</h4><p className="mt-2 text-sm text-slate-500">Renseignez l’identifiant de propriété et configurez le compte de service Google sur le serveur pour afficher vos statistiques réelles. Aucun chiffre fictif n’est affiché.</p></section>:<>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Utilisateurs actifs",report.metrics.users.toLocaleString("fr-CA")],["Sessions",report.metrics.sessions.toLocaleString("fr-CA")],["Pages vues",report.metrics.views.toLocaleString("fr-CA")],["Taux d’engagement",`${(report.metrics.engagementRate*100).toFixed(1)} %`]].map(([title,value])=><article key={title} className="card"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 font-heading text-2xl font-semibold text-brand-600">{value}</p><p className="mt-1 text-xs text-slate-500">Google Analytics · {days} jours</p></article>)}</section>
      <section className="card"><h4 className="mb-4 font-heading text-lg font-semibold">Évolution des sessions</h4>{report.series.length?<div className="h-64"><Line options={options} data={{labels:report.series.map(row=>`${row.day.slice(6,8)}/${row.day.slice(4,6)}`),datasets:[{label:"Sessions",data:report.series.map(row=>row.sessions),borderColor:"#0B3C5D",backgroundColor:"rgba(11,60,93,.12)",tension:.35,fill:true}]}}/></div>:<p className="text-sm text-slate-500">Aucune session enregistrée sur cette période.</p>}</section>
      <div className="grid gap-4 xl:grid-cols-2">{[["Sources d’acquisition",report.sources,"name","sessions"],["Pages les plus consultées",report.pages,"path","views"]].map(([title,items,key,metric])=><section className="card" key={title}><h4 className="mb-4 font-heading text-lg font-semibold">{title}</h4>{!items.length?<p className="text-sm text-slate-500">Aucune donnée sur cette période.</p>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="pb-3 text-left">{key==="name"?"Canal":"Page"}</th><th className="pb-3 text-right">{metric==="views"?"Vues":"Sessions"}</th></tr></thead><tbody>{items.map(row=><tr key={row[key]} className="border-b border-slate-100"><td className="py-3 pr-4 break-all">{row[key]}</td><td className="py-3 text-right font-semibold">{row[metric]}</td></tr>)}</tbody></table></div>}</section>)}</div>
      <p className="text-xs text-slate-500">Rapport récupéré le {new Date(report.fetchedAt).toLocaleString("fr-CA")}. Cache serveur de cinq minutes ; les statistiques Google ne sont pas un suivi en temps réel.</p>
    </>}
    <section className="card"><h3 className="mb-4 font-heading text-lg font-semibold">Configuration GA4</h3>{!config?<p className="text-sm text-slate-500">{saveError||"Chargement…"}</p>:<form className="space-y-4" onSubmit={save}>
      <div className="grid gap-4 sm:grid-cols-2"><div><label htmlFor="ga4-measurement" className="field-label">Identifiant de mesure</label><input id="ga4-measurement" className="field-input" placeholder="G-XXXXXXXXXX" maxLength={30} disabled={busy} value={config.measurementId} onChange={e=>setConfig({...config,measurementId:e.target.value})}/></div><div><label htmlFor="ga4-property" className="field-label">Identifiant numérique de propriété</label><input id="ga4-property" className="field-input" placeholder="123456789" maxLength={20} inputMode="numeric" disabled={busy} value={config.propertyId} onChange={e=>setConfig({...config,propertyId:e.target.value})}/></div></div>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={busy} checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/>Activer le suivi des pages publiques après consentement du visiteur</label>
      <p className="text-sm text-slate-500">Seuls l’accueil, les tarifs et la page de connexion sont suivis. Les écrans CRM, les formulaires de récupération et les portails privés sont exclus. Aucun nom, email, montant de facture ou jeton privé n’est envoyé.</p>
      <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} required={config.enabled} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>J’ai désactivé la mesure améliorée automatique du flux Web GA4 pour conserver uniquement les pages vues contrôlées par l’application.</label>
      <p className="text-sm text-slate-500">Rapports API : {config.credentialsConfigured?"fichier de compte de service configuré sur le serveur":"compte de service Google à configurer sur le serveur"}. Sa clé privée ne se saisit jamais dans ce formulaire.</p>
      <div><label className="field-label" htmlFor="ga4-reason">Motif du changement</label><input id="ga4-reason" className="field-input" minLength={10} maxLength={500} required disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></div>
      {saveError&&<p role="alert" className="text-sm text-red-600">{saveError}</p>}{saved&&<p role="status" className="text-sm text-teal-700">{saved}</p>}
      <div className="flex flex-wrap gap-2"><button className="btn-primary" disabled={busy}>{busy?"Enregistrement…":"Enregistrer la configuration"}</button><a className="btn-secondary" href={config.propertyId?`https://analytics.google.com/analytics/web/#/p${config.propertyId}/reports/reportinghub`:"https://analytics.google.com/"} target="_blank" rel="noopener noreferrer">Ouvrir Google Analytics</a></div>
    </form>}</section>
  </div>;
}
